export const SET_PAGETYPE = 'SET_PAGETYPE';

export const RECIPE_FECHING = 'RECIPE_FECHING';

export const SET_RECIPIES = 'SET_RECIPIES';

export const SET_MEALS_CATEGORIES = 'SET_MEALS_CATEGORIES';

export const SET_DRINKS_CATEGORIES = 'SET_DRINKS_CATEGORIES';
